export const LOGIN_TYPE = {
  INITIAL_LOGIN_FORM: "login/INITIAL_LOGIN_FORM",
  LOGIN_START: "login/LOGIN_START",
  LOGIN_SUCCESS: "login/LOGIN_SUCCESS",
  LOGIN_FAILED: "login/LOGIN_FAILED",
  LOGIN_OAUTH_START: "login/LOGIN_OAUTH_START",
  LOGIN_OAUTH_SUCCESS: "login/LOGIN_OAUTH_SUCCESS",
  LOGIN_OAUTH_FAILED: "login/LOGIN_OAUTH_FAILED",
  REFRESH_TOKEN_START: "refresh/REFRESH_TOKEN_START",
  REFRESH_TOKEN_SUCCESS: "refresh/REFRESH_TOKEN_SUCCESS",
  REFRESH_TOKEN_FAILED: "refresh/REFRESH_TOKEN_FAILED",
};
